# Generated by Django 2.1.8 on 2019-07-21 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstFirst', models.FloatField()),
                ('firstSecond', models.FloatField()),
                ('secondFirst', models.FloatField()),
                ('secondSecond', models.FloatField()),
                ('thirdFirst', models.FloatField()),
                ('thirdSecond', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TargetUniv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('univ', models.CharField(max_length=30)),
                ('major', models.CharField(max_length=30)),
                ('applyType', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('koreanPoint', models.IntegerField()),
                ('koreanGrade', models.IntegerField()),
                ('mathPoint', models.IntegerField()),
                ('mathGrade', models.IntegerField()),
                ('englishPoint', models.IntegerField()),
                ('englishGrade', models.IntegerField()),
                ('tamguFirstName', models.CharField(max_length=20)),
                ('tamguFirstGrade', models.IntegerField()),
                ('tamguFirstPoint', models.IntegerField()),
                ('tamguSecondName', models.CharField(max_length=20)),
                ('tamguSecondGrade', models.IntegerField()),
                ('tamguSecondPoint', models.IntegerField()),
                ('foreignName', models.CharField(max_length=20)),
                ('foreignGrade', models.IntegerField()),
                ('foreignPoint', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
